FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_USER_API_URL
ARG VITE_EVENT_API_URL
ARG VITE_BOOKING_API_URL
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_FACEBOOK_APP_ID
ARG VITE_OAUTH_REDIRECT_BASE_URL
ARG VITE_TMDB_API_TOKEN

ENV VITE_USER_API_URL=$VITE_USER_API_URL
ENV VITE_EVENT_API_URL=$VITE_EVENT_API_URL
ENV VITE_BOOKING_API_URL=$VITE_BOOKING_API_URL
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_FACEBOOK_APP_ID=$VITE_FACEBOOK_APP_ID
ENV VITE_OAUTH_REDIRECT_BASE_URL=$VITE_OAUTH_REDIRECT_BASE_URL
ENV VITE_TMDB_API_TOKEN=$VITE_TMDB_API_TOKEN

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]